spring.application.name=lex-emotion-api

reddit.client.redirect_uri=http://localhost:8080

reddit.baseUrl=https://www.reddit.com/r/brasil
reddit.clientId=xblpJ0cCfV_AXIJ9OTLRrA
reddit.clientSecret=_OqJNDhAWPK3Ilwo9ibJA5ckFEBQ2A
reddit.username=carlosbarbosal
reddit.password=A152188a
reddit.userAgent=JavaRedditClient/0.1

